// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: ariston.proto

package arimsgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParametersMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp      int64               `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Params         []*Parameter        `protobuf:"bytes,5000,rep,name=params,proto3" json:"params,omitempty"`
	ParamLimitsMsg *ParameterLimitsMsg `protobuf:"bytes,5001,opt,name=param_limits_msg,json=paramLimitsMsg,proto3" json:"param_limits_msg,omitempty"`
}

func (x *ParametersMsg) Reset() {
	*x = ParametersMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ariston_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParametersMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParametersMsg) ProtoMessage() {}

func (x *ParametersMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ariston_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParametersMsg.ProtoReflect.Descriptor instead.
func (*ParametersMsg) Descriptor() ([]byte, []int) {
	return file_ariston_proto_rawDescGZIP(), []int{0}
}

func (x *ParametersMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ParametersMsg) GetParams() []*Parameter {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ParametersMsg) GetParamLimitsMsg() *ParameterLimitsMsg {
	if x != nil {
		return x.ParamLimitsMsg
	}
	return nil
}

type Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Something1 int32  `protobuf:"varint,2,opt,name=something1,proto3" json:"something1,omitempty"`
	// Types that are assignable to Value:
	//
	//	*Parameter_ValueI
	//	*Parameter_ValueS
	Value isParameter_Value `protobuf_oneof:"value"`
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ariston_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_ariston_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_ariston_proto_rawDescGZIP(), []int{1}
}

func (x *Parameter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Parameter) GetSomething1() int32 {
	if x != nil {
		return x.Something1
	}
	return 0
}

func (m *Parameter) GetValue() isParameter_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Parameter) GetValueI() int32 {
	if x, ok := x.GetValue().(*Parameter_ValueI); ok {
		return x.ValueI
	}
	return 0
}

func (x *Parameter) GetValueS() string {
	if x, ok := x.GetValue().(*Parameter_ValueS); ok {
		return x.ValueS
	}
	return ""
}

type isParameter_Value interface {
	isParameter_Value()
}

type Parameter_ValueI struct {
	ValueI int32 `protobuf:"varint,6,opt,name=value_i,json=valueI,proto3,oneof"`
}

type Parameter_ValueS struct {
	ValueS string `protobuf:"bytes,8,opt,name=value_s,json=valueS,proto3,oneof"`
}

func (*Parameter_ValueI) isParameter_Value() {}

func (*Parameter_ValueS) isParameter_Value() {}

type ParameterLimit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Min int32  `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max int32  `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *ParameterLimit) Reset() {
	*x = ParameterLimit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ariston_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParameterLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterLimit) ProtoMessage() {}

func (x *ParameterLimit) ProtoReflect() protoreflect.Message {
	mi := &file_ariston_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterLimit.ProtoReflect.Descriptor instead.
func (*ParameterLimit) Descriptor() ([]byte, []int) {
	return file_ariston_proto_rawDescGZIP(), []int{2}
}

func (x *ParameterLimit) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ParameterLimit) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ParameterLimit) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type ParameterLimitsMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParamLimits []*ParameterLimit `protobuf:"bytes,1,rep,name=param_limits,json=paramLimits,proto3" json:"param_limits,omitempty"`
}

func (x *ParameterLimitsMsg) Reset() {
	*x = ParameterLimitsMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ariston_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParameterLimitsMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterLimitsMsg) ProtoMessage() {}

func (x *ParameterLimitsMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ariston_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterLimitsMsg.ProtoReflect.Descriptor instead.
func (*ParameterLimitsMsg) Descriptor() ([]byte, []int) {
	return file_ariston_proto_rawDescGZIP(), []int{3}
}

func (x *ParameterLimitsMsg) GetParamLimits() []*ParameterLimit {
	if x != nil {
		return x.ParamLimits
	}
	return nil
}

type Consumption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsumptionTimeInterval int32   `protobuf:"varint,1,opt,name=consumption_time_interval,json=consumptionTimeInterval,proto3" json:"consumption_time_interval,omitempty"`
	ConsumptionType         int32   `protobuf:"varint,2,opt,name=consumption_type,json=consumptionType,proto3" json:"consumption_type,omitempty"`
	Whs                     []int32 `protobuf:"varint,3,rep,packed,name=whs,proto3" json:"whs,omitempty"`
}

func (x *Consumption) Reset() {
	*x = Consumption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ariston_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consumption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consumption) ProtoMessage() {}

func (x *Consumption) ProtoReflect() protoreflect.Message {
	mi := &file_ariston_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consumption.ProtoReflect.Descriptor instead.
func (*Consumption) Descriptor() ([]byte, []int) {
	return file_ariston_proto_rawDescGZIP(), []int{4}
}

func (x *Consumption) GetConsumptionTimeInterval() int32 {
	if x != nil {
		return x.ConsumptionTimeInterval
	}
	return 0
}

func (x *Consumption) GetConsumptionType() int32 {
	if x != nil {
		return x.ConsumptionType
	}
	return 0
}

func (x *Consumption) GetWhs() []int32 {
	if x != nil {
		return x.Whs
	}
	return nil
}

type ConsumptionMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp    int64         `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Params       []*Parameter  `protobuf:"bytes,5000,rep,name=params,proto3" json:"params,omitempty"`
	Consumptions *Consumptions `protobuf:"bytes,5001,opt,name=consumptions,proto3" json:"consumptions,omitempty"`
}

func (x *ConsumptionMsg) Reset() {
	*x = ConsumptionMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ariston_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumptionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionMsg) ProtoMessage() {}

func (x *ConsumptionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ariston_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionMsg.ProtoReflect.Descriptor instead.
func (*ConsumptionMsg) Descriptor() ([]byte, []int) {
	return file_ariston_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumptionMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConsumptionMsg) GetParams() []*Parameter {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ConsumptionMsg) GetConsumptions() *Consumptions {
	if x != nil {
		return x.Consumptions
	}
	return nil
}

type Consumptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Consumptions []*Consumption `protobuf:"bytes,1,rep,name=consumptions,proto3" json:"consumptions,omitempty"`
}

func (x *Consumptions) Reset() {
	*x = Consumptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ariston_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consumptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consumptions) ProtoMessage() {}

func (x *Consumptions) ProtoReflect() protoreflect.Message {
	mi := &file_ariston_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consumptions.ProtoReflect.Descriptor instead.
func (*Consumptions) Descriptor() ([]byte, []int) {
	return file_ariston_proto_rawDescGZIP(), []int{6}
}

func (x *Consumptions) GetConsumptions() []*Consumption {
	if x != nil {
		return x.Consumptions
	}
	return nil
}

var File_ariston_proto protoreflect.FileDescriptor

var file_ariston_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x72, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x61, 0x72, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x22, 0xa2, 0x01, 0x0a, 0x0d, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2b, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x88, 0x27, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x72, 0x69, 0x73,
	0x74, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x46, 0x0a, 0x10, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x89, 0x27, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x61, 0x72, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x4d, 0x73, 0x67, 0x52, 0x0e, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x4d, 0x73, 0x67, 0x22, 0x7c, 0x0a,
	0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x31, 0x12, 0x19, 0x0a, 0x07,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x12, 0x19, 0x0a, 0x07, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x5f, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x53, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x46, 0x0a, 0x0e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x69,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6d, 0x61, 0x78, 0x22, 0x50, 0x0a, 0x12, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x3a, 0x0a, 0x0c, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x61, 0x72, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x19, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x77, 0x68, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x77, 0x68, 0x73, 0x22, 0x97,
	0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73,
	0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x2b, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x88, 0x27, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x61, 0x72, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x3a, 0x0a, 0x0c,
	0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x89, 0x27, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x72, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x48, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x72, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x61, 0x72, 0x69, 0x6d, 0x73, 0x67, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ariston_proto_rawDescOnce sync.Once
	file_ariston_proto_rawDescData = file_ariston_proto_rawDesc
)

func file_ariston_proto_rawDescGZIP() []byte {
	file_ariston_proto_rawDescOnce.Do(func() {
		file_ariston_proto_rawDescData = protoimpl.X.CompressGZIP(file_ariston_proto_rawDescData)
	})
	return file_ariston_proto_rawDescData
}

var file_ariston_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ariston_proto_goTypes = []interface{}{
	(*ParametersMsg)(nil),      // 0: ariston.ParametersMsg
	(*Parameter)(nil),          // 1: ariston.Parameter
	(*ParameterLimit)(nil),     // 2: ariston.ParameterLimit
	(*ParameterLimitsMsg)(nil), // 3: ariston.ParameterLimitsMsg
	(*Consumption)(nil),        // 4: ariston.Consumption
	(*ConsumptionMsg)(nil),     // 5: ariston.ConsumptionMsg
	(*Consumptions)(nil),       // 6: ariston.Consumptions
}
var file_ariston_proto_depIdxs = []int32{
	1, // 0: ariston.ParametersMsg.params:type_name -> ariston.Parameter
	3, // 1: ariston.ParametersMsg.param_limits_msg:type_name -> ariston.ParameterLimitsMsg
	2, // 2: ariston.ParameterLimitsMsg.param_limits:type_name -> ariston.ParameterLimit
	1, // 3: ariston.ConsumptionMsg.params:type_name -> ariston.Parameter
	6, // 4: ariston.ConsumptionMsg.consumptions:type_name -> ariston.Consumptions
	4, // 5: ariston.Consumptions.consumptions:type_name -> ariston.Consumption
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ariston_proto_init() }
func file_ariston_proto_init() {
	if File_ariston_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ariston_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParametersMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ariston_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ariston_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParameterLimit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ariston_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParameterLimitsMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ariston_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consumption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ariston_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumptionMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ariston_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consumptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ariston_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Parameter_ValueI)(nil),
		(*Parameter_ValueS)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ariston_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ariston_proto_goTypes,
		DependencyIndexes: file_ariston_proto_depIdxs,
		MessageInfos:      file_ariston_proto_msgTypes,
	}.Build()
	File_ariston_proto = out.File
	file_ariston_proto_rawDesc = nil
	file_ariston_proto_goTypes = nil
	file_ariston_proto_depIdxs = nil
}
